% -------------------------------------------------------------------
%  Generated by MATLAB on 9-Jun-2018 17:00:26
%  MATLAB version: 9.2.0.538062 (R2017a)
% -------------------------------------------------------------------
saveVarsMat = load('homo.mat');

H01 = saveVarsMat.H01; % <1x1 sym> unsupported class

H02 = saveVarsMat.H02; % <1x1 sym> unsupported class

H03 = saveVarsMat.H03; % <1x1 sym> unsupported class

H04 = saveVarsMat.H04; % <1x1 sym> unsupported class

H12 = saveVarsMat.H12; % <1x1 sym> unsupported class

H23 = saveVarsMat.H23; % <1x1 sym> unsupported class

H34 = saveVarsMat.H34; % <1x1 sym> unsupported class

J = saveVarsMat.J; % <1x1 sym> unsupported class

J11 = saveVarsMat.J11; % <1x1 sym> unsupported class

Jv = saveVarsMat.Jv; % <1x1 sym> unsupported class

Jw = saveVarsMat.Jw; % <1x1 sym> unsupported class

O0 = [0; 0; 0];

O1 = saveVarsMat.O1; % <1x1 sym> unsupported class

O2 = saveVarsMat.O2; % <1x1 sym> unsupported class

O3 = saveVarsMat.O3; % <1x1 sym> unsupported class

O4 = saveVarsMat.O4; % <1x1 sym> unsupported class

Sig = saveVarsMat.Sig; % <1x1 sym> unsupported class

Sigx = saveVarsMat.Sigx; % <1x1 sym> unsupported class

Sigy = saveVarsMat.Sigy; % <1x1 sym> unsupported class

Sigz = saveVarsMat.Sigz; % <1x1 sym> unsupported class

X = saveVarsMat.X; % <1x1 sym> unsupported class

Y = saveVarsMat.Y; % <1x1 sym> unsupported class

Z = saveVarsMat.Z; % <1x1 sym> unsupported class

Z0 = [0; 0; 1];

Z1 = saveVarsMat.Z1; % <1x1 sym> unsupported class

Z2 = saveVarsMat.Z2; % <1x1 sym> unsupported class

Z3 = saveVarsMat.Z3; % <1x1 sym> unsupported class

a1 = saveVarsMat.a1; % <1x1 sym> unsupported class

a2 = saveVarsMat.a2; % <1x1 sym> unsupported class

d1 = saveVarsMat.d1; % <1x1 sym> unsupported class

d3v = saveVarsMat.d3v; % <1x1 sym> unsupported class

d4 = saveVarsMat.d4; % <1x1 sym> unsupported class

th1v = saveVarsMat.th1v; % <1x1 sym> unsupported class

th2v = saveVarsMat.th2v; % <1x1 sym> unsupported class

th4v = saveVarsMat.th4v; % <1x1 sym> unsupported class

ud = saveVarsMat.ud; % <1x1 sym> unsupported class

uth = saveVarsMat.uth; % <1x1 sym> unsupported class

ux = saveVarsMat.ux; % <1x1 sym> unsupported class

uy = saveVarsMat.uy; % <1x1 sym> unsupported class

uz = saveVarsMat.uz; % <1x1 sym> unsupported class

clear saveVarsMat;
